export const EndPoints = {
    GetAllUserType: "usertype",
    Login: 'login',
    SetQBUserId: 'setqbuserid',
    // Teacher
    GetLessionById: 'getalllesson',
    GetMyDayByTeacherId: 'getmydayteacher',
    PupilByTeacherId: 'pupilbyteacherid',
    GetTimeTable: 'gettimetable',
    CalenderEvent: 'calenderevent',
    AllEventHomworklesson:"allEventHomworklesson",
    AllEventHomworklessonpupil:"allEventHomworklessonpupil",
    GetSubjectBySchoolId: 'subjectbyschoolid/',
    GetParticipants: 'getparticipants/',
    GetPupilByTeacherId: 'pupilbyteacherid/',
    Homework: "homework",
    HomeworkUpdate: 'homeworkupdate',
    Lesson: 'lesson',
    LessonUpdate: 'lessonupdate/',
    LessonMaterialUpload: 'lessonmaterialupload/',
    HomeworkMaterialUpload: 'homeworkmaterialupload/',
    TeacherMarkedHomework: 'teacherMarkedHomework',
    EventType: 'eventtype',
    HomeworkSubmited: 'homeworksubmited/',
    Groupsetup: 'groupsetup',

    //Pupil
    PupilRegister:"pupilregister",
    GetListOfPupilMyDay: "getmydaypupil",
    GetHomeworkListByPupil:"pupilhomeworklist",
    GetAllHomeworkListByPupil:"allpupilhomeworklist",
    GetTimeTablePupil:'gettimetablepupil',
    GetAllPupilLessonList:'allpupillessonlist',
    PupilUploadHomework:"uploadhomework",
    UploadWorkspace:'uploadWorkspace',
    GetPupilLesson: 'getpupillesson',
    GetPupilHomework: 'getpupilhomework',

    // pupil management.
    PupilByTeacherId:"pupilbyteacherid",
    UserSetting:"usersetting",
}