export const EndPoints = {
    GetAllUserType: "usertype",
    Login: 'login',
    SetQBUserId: 'setqbuserid',
    // Teacher
    GetLessionById: 'getalllesson',
    GetMyDayByTeacherId: 'getmydayteacher',
    PupilByTeacherId: 'pupilbyteacherid',
    GetTimeTable: 'gettimetable',
    CalenderEvent: 'calenderevent',
    AllEventHomworklesson:"allEventHomworklesson",
    AllEventHomworklessonpupil:"allEventHomworklessonpupil",
    GetSubjectBySchoolId: 'subjectbyschoolid/',
    GetParticipants: 'getparticipants/',
    GetPupilByTeacherId: 'pupilbyteacherid/',
    Homework: "homework",
    HomeworkUpdate: 'homeworkupdate',
    Lesson: 'lesson',
    LessonUpdate: 'lessonupdate/',
    LessonMaterialUpload: 'lessonmaterialupload/',
    HomeworkMaterialUpload: 'homeworkmaterialupload/',
    TeacherMarkedHomework: 'teacherMarkedHomework',
    EventType: 'eventtype',
    HomeworkSubmited: 'homeworksubmited/',
    Groupsetup: 'groupsetup',
    UpdateGroupSetup: 'updategroupsetup',
    PupilSchoolCode: 'pupilschoolcode',
    GlobalMessaging: 'globalmessaging',
    ParentList: 'parentlist',
    PupilGlobalMessaging: 'pupilglobalmessaging',
    UpdateGlobalMessaging: 'updateglobalmessaging',
    GetCountLession: 'getcountlession',
    GetCountHomework: 'getcounthomework',

    //Pupil
    PupilRegister:"pupilregister",
    GetListOfPupilMyDay: "getmydaypupil",
    GetHomeworkListByPupil:"pupilhomeworklist",
    GetAllHomeworkListByPupil:"allpupilhomeworklist",
    GetTimeTablePupil:'gettimetablepupil',
    GetAllPupilLessonList:'allpupillessonlist',
    PupilUploadHomework:"uploadhomework",
    UploadWorkspace:'uploadWorkspace',
    GetPupilLesson: 'getpupillesson',
    GetPupilHomework: 'getpupilhomework',
    PupilUpdate: 'pupilupdate',
    UpdateParent: 'updateparent',
    SaveLessonByPupil: 'savelessionbypupil',
    GetPupilRewards: 'getpupilrewards',

    // pupil management.
    PupilByTeacherId:"pupilbyteacherid",

    //Parent Zone
    SetPin: 'setpin',
    UserSetting:"usersetting",
    SaveSetting:"saveSetting",

    LessionStartEnd:"lessionstartend",
    LessonCheck:"lessoncheck",
    AddInstantReward: 'addinstantreward',
    PupilUploadProfile: 'pupiluploadProfile',
    TeacherUploadProfile: 'teacheruploadProfile',
    GetTeachersList: 'getteacherslist',

    GetAllTeacher:"teacher",
    TeacherBySchoolId: 'teacherbyschoolid',
    TeacherDetails: 'teacherdetails',
    PupilByShoolId: 'pupilbyschoolid',
    GetClassSetup: 'getclasssetup',
    PupilUpload: 'pupilupload',
    TeacherUpload: 'teacherupload',
    Pupil: 'pupil',
    Teacher: 'teacher',
    Title: 'title',
    TeachingYear: 'teachingyear',
    ClassSetup: 'classsetup',

    //
    SaveLessionRecord:"lessionrecord",

    //
    getAllNotifications : 'getnotifocation',
    deleteNotification : 'notificationdelete'
}