export const EndPoints = {
    Login: 'login',
    GetLessionById: 'getalllesson',
    PupilByTeacherId: 'pupilbyteacherid',
    GetTimeTable: 'gettimetable',
    CalenderEvent:'calenderevent/',
    GetSubjectBySchoolId:'subjectbyschoolid/',
    GetParticipants:'getparticipants/',
    GetPupilByTeacherId:'pupilbyteacherid/',
    Homework:"homework",
    Lesson: 'lesson',
    LessonUpdate: 'lessonupdate/',
    LessonMaterialUpload: 'lessonmaterialupload/',
    EventType: 'eventtype',
}