require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'OpenSchool' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'QuickBlox' #'~> 2.17.10'
  pod 'Quickblox-WebRTC' #'~> 2.7.6'
  pod "PubNub"
  pod 'SDWebImage', '~> 4.4.7'
  pod 'TTTAttributedLabel', '~> 2.0.0'
#  pod 'SVProgressHUD'
#  pod 'SVProgressHUD'
#  pod 'SDWebImage', '~> 4.4.7'
#  pod 'TTTAttributedLabel', '~> 2.0.0'
  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # target 'OpenSchoolTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  
  post_install do |installer|
       installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
               config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
           end
       end
   end
end

# target 'OpenSchool-tvOS' do
#   # Pods for OpenSchool-tvOS

#   target 'OpenSchool-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
