const COLORS = {
    black: '#000000',
    white: '#FFFFFF',
    transparent: 'transparent',
    lightplaceholder: '#676693',
    blueButton: '#5381F8',
    themeBlue: '#03014C',
    thmePurple: '#5F34F5',
    darkGray: '#262626',
    lightGray: '#9699A5',
    buttonGreen: '#049160',
    menuLightFonts: '#B4B6BE',
    bottomProfileLightBorder:'#F1F2F7',
    backgroundColorCommon: '#F9FAFC',
    red: '#FF200D',
    orage: '#FFB100',
    dashboardBorder: '#ECEDF2',
    dashboardPupilBlue: '#50A7F0',
    lightGreen: '#C4F7D2',
    lightYellow: '#FFE882',
    lightPurple: '#FED9FF',
    lightBlue: '#BFE6FF',
    selectedDashboard: '#F5F7FB',
    borderGrp: '#DCDCE2',
    grpColor: '#4E4E4E',
    commonBorderColor: '#ECEDF2',
    dashboardGreenButton: '#00A36B',
    purpleDark: '#BC8BFF',
    yellowDark: '#FFAD12',
    lightGrayPupil: '#ECEDF0',
    dashboardHomeWorkPurple: '#BC8BFD',
    videoLinkBorder: '#E7E9EF',
    greyplaceholder: '#262626',
}

export default COLORS;