const Images = {
    Chat: require('../assets/images/chat2.png'),
    Logo: require('../assets/images/logo2.png'),
    GradientBack: require('../assets/images/teacher_intro_screen_bg2.png'),
    UserIcon: require('../assets/images/userIcon.png'),
    LoginBack: require('../assets/images/ILLUS-login.png'),
    UserIconLogin: require('../assets/images/icouser2.png'),
    Password: require('../assets/images/icopassword2.png'),
    ShowPassword: require('../assets/images/icoview2.png'),
    HidePassword: require('../assets/images/hide-password2.png'),
    DayIcon: require('../assets/images/myDay3.png'),
    calnderDashHeaderIcon: require('../assets/images/calendar-dashboard2.png'),
    MoreLinks: require('../assets/images/dashBoardMorelink2.png'),
    PupilDashIcon: require('../assets/images/pupilIcon2.png'),
    BronzeStar: require('../assets/images/bronze-star2.png'),
    SilverStar: require('../assets/images/silver-star2.png'),
    GoldStar: require('../assets/images/gold-star2.png'),
    BronzeStarFill: require('../assets/images/bronzeStarFill2.png'),
    SilverStarFill: require('../assets/images/silverStarFill2.png'),
    GoldStarFill: require('../assets/images/goldStarSelected2.png'),
    DashboardRightArrow: require('../assets/images/right-arrow2.png'),
    DashboardCallIcon: require('../assets/images/callDashboard2.png'),
    LessonIcon: require('../assets/images/lessonIcon2.png'),
    ImageIcon: require('../assets/images/calenderIcon2.png'),
    PupilGrpIcon: require('../assets/images/pupilgrpIcon2.png'),
    Myday: require('../assets/images/myDay3.png'),
    CalenderIconSmall: require('../assets/images/calendar-small-icon2.png'),
    Clock: require('../assets/images/clock2.png'),
    Group: require('../assets/images/group2.png'),
    AttachmentIcon: require('../assets/images/attachment2.png'),
    CheckIcon: require('../assets/images/check-icon2.png'),
    PupilDashTopBg: require('../assets/images/pupilDashboardTopGridBg2.png'),
    CalenderBg: require('../assets/images/calendarBg2.png'),
    PupilHomeworkTableTopBg: require('../assets/images/pupilHomeworkTableTopBg2.png'),
    HomeworkBook: require('../assets/images/homeworkbook2.png'),
    DueToday: require('../assets/images/dueToday2.png'),
    DueCalendar: require('../assets/images/dueCalendar2.png'),
    SubIcon: require('../assets/images/subjectIcon2.png'),
    CheckedSqure: require('../assets/images/checkedSquare2.png'),
    RewardStar: require('../assets/images/reward-stars2.png'),
    BronzeStarFill: require('../assets/images/bronzeStarFill2.png'),
    SilverStarFill: require('../assets/images/silverStarFill3.png'),
    GoldStarFill: require('../assets/images/goldStarSelected2.png'),
    Robot: require('../assets/images/achivement-robot2.png'),
    ProfileBack: require('../assets/images/profileBack.png'),
    Dashboard: require('../assets/images/dashboard2.png'),
    Teacher: require('../assets/images/teachers2.png'),
    Pupil: require('../assets/images/pupils2.png'),
    Messaging: require('../assets/images/messaging.png'),
    Parents: require('../assets/images/parents2.png'),
    Faqs: require('../assets/images/faq2.png'),
    ProfileBackSideMenu: require('../assets/images/profileBack.png'),
    SidebarMore: require('../assets/images/more2.png'),
    Notification: require('../assets/images/notification2.png'),
    SearchIcon: require('../assets/images/search2.png'),
    FilterIcon: require('../assets/images/filter2.png'),
    AddIconWhite: require('../assets/images/addIcon2.png'),
    PopupCloseIcon: require('../assets/images/cancel2.png'),
    Edit: require('../assets/images/edit3.png'),
    NewLessons: require('../assets/images/new-lesson2.png'),
    NewEvents: require('../assets/images/new-event2.png'),
    UploadCalender: require('../assets/images/upload-calendar2.png'),
    CheckIconWhite: require('../assets/images/white-check-icon2.png'),
    Download: require('../assets/images/download2.png'),
    VideoUpload: require('../assets/images/video-uploads2.png'),
    RecordIcon: require('../assets/images/recording-icon2.png'),
    AddIcon: require('../assets/images/add2.png'),
    PlayIcon: require('../assets/images/playIcon2.png'),
    DropHolder: require('../assets/images/dropHolder2.png'),
    bbcImage: require('../assets/images/bbc-video2.png'),
    PlayTransperent: require('../assets/images/play-transparent-icon2.png'),
    TickSelected: require('../assets/images/tick-selected2.png'),
    TickUnselected: require('../assets/images/unselected2.png'),
    TedVideo: require('../assets/images/ted-video2.png'),
    SearchGarden: require('../assets/images/scratch-garden2.png'),
    RainForest: require('../assets/images/amazing-rainforest2.png'),
    DreamWorks: require('../assets/images/dream-works2.png'),
    GardenNew: require('../assets/images/scratch-garden-new2.png'),
    KidsNet: require('../assets/images/kids-nat-geo2.png'),
    Marcked: require('../assets/images/marked2.png'),
    UploadHomeWork: require('../assets/images/upload-hw2.png'),
    VideoBack: require('../assets/images/video-back2.png'),
    VideoShadow: require('../assets/images/video-shadow2.png'),
    BookmarkIcon: require('../assets/images/bookmark-on2.png'),
    BookmarkIconOff: require('../assets/images/bookmarkOff2.png'),
    UserProfilePopup: require('../assets/images/userProfilePopup.png'),
    MyLessons: require('../assets/images/my-lessons2.png'),
    MyAchievements: require('../assets/images/my-achievements2.png'),
    MyAvatar: require('../assets/images/my-avatar2.png'),
    OpenSchool: require('../assets/images/open-school2.png'),
    cartoon: require('../assets/images/cartoon2.png'),
    backArrow: require('../assets/images/back-arrow2.png'),
    DropArrow: require('../assets/images/down-arrow2.png'),
    timeTableClock: require('../assets/images/timetable-clock2.png'),
    trashIcon: require('../assets/images/trash2.png'),
    ScreenAndCameraRecordingBack: require('../assets/images/image-amazon2.png'),
    recordingTimerIcon: require('../assets/images/recording-timer2.png'),
    moreHorizontal: require('../assets/images/more-horizontal2.png'),
    recordButton: require('../assets/images/stop2.png'),
    pauseButton: require('../assets/images/play-pause2.png'),
    Play3Icon:require('../assets/images/play3.png'),
    userVideo: require('../assets/images/teacher-user2.png'),
    pdfIcon: require('../assets/images/file2.png'),
    schoolLoginIcon: require('../assets/images/school-icon.png'),
    teacherLoginIcon: require('../assets/images/teacher-icon.png'),
    pupilLoginIcon: require('../assets/images/pupil-icon.png'),
    illuTopBg: require('../assets/images/illus-top.png'),
    loginMainBackteacher: require('../assets/images/loginMaintopteacher2.png'),
    introSlideOne: require('../assets/images/pupil-intro-screen-1_2.png'),
    introSlideTwo: require('../assets/images/pupil-intro-screen-2_2.png'),
    introSlideThree: require('../assets/images/pupil-intro-screen-3_2.png'),
    teacherintroSlideOne: require('../assets/images/teacher-intro-illus-1-2.png'),
    teacherintroSlideTwo: require('../assets/images/teacher-intro-illus-2-2.png'),
    teacherintroSlideThree: require('../assets/images/teacher-intro-illus-3-2.png'),
    managementBlankImg: require('../assets/images/pupil-management-image2.png'),
    managementBlockTopImg: require('../assets/images/management-detail-banner2.png'),
    chartImg:require('../assets/images/management-chart2.png'),
    purpleMarkImg:require('../assets/images/purple-dot2.png'),
    orangeMarkImg:require('../assets/images/orange-dot2.png'),
    graphImg:require('../assets/images/management-graph2.png'),
    parentZone1:require('../assets/images/parent-zone-1-2.png'),
    parentZone2:require('../assets/images/parent-zone-2-2.png'),
    parentZoneAdd:require('../assets/images/parent-zone-3-2.png'),
    parentZoneIcon: require('../assets/images/parent-zone-icon2.png'),
    editIcon: require('../assets/images/edit-icon2.png'),
    noData: require('../assets/images/no-data2.png'),
    backSpaceArrow: require('../assets/images/backSpace-mobile-2.png'),

    // Chat Icon
    attachmentIpad:require('../assets/images/Chatimage/attachment-ipad.png'),
    paperClip:require('../assets/images/Chatimage/paperclip.png'),
    send:require('../assets/images/Chatimage/send.png'),
    imageUpload:require('../assets/images/Chatimage/image-upload.png'),
}
export default Images;