import { Dimensions, Platform, StyleSheet } from 'react-native'
import COLORS from '../../../../utils/Colors';
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
import FONTS from '../../../../utils/Fonts';
import { color } from 'react-native-reanimated';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    mainPage: {
        flexDirection: 'row',
        flex: 1,
        backgroundColor: COLORS.backgroundColorCommon,
    },
    myDay: {
        backgroundColor: COLORS.orage,
        paddingRight: hp(2.60),
        paddingLeft: hp(1.60),
        position: 'relative',
        flexDirection: 'row',
        borderRadius: hp(1),
        justifyContent: 'space-between',
        height: hp(8.5),
        zIndex: 9,
    },
    rightContent: {
        flexDirection: 'row',
    },
    ScrollViewFlatlist:{
        height: hp(60),
    },
    dayIcon: {
        width: hp(4),
        resizeMode: 'contain',
    },
    dayTitle: {
        color: COLORS.white,
        fontSize: hp(2.34),
        fontFamily: FONTS.fontBold,
        paddingLeft: hp(1.30),
        paddingTop: hp(1),
    },
    datePositionBg: {
        position: 'absolute',
        top: -38,
        right: 42,
        textAlign: 'center',
        paddingVertical: 20.5,
        paddingLeft: 20,
        paddingRight: 25,
        width: 102,
        height: 81,
        resizeMode: 'contain',
    },
    date: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontBold,
        color: COLORS.darkGrayIntro,
        textAlign: 'center',
        marginBottom: hp(0.3),
    },
    whiteBoard: {
        backgroundColor: COLORS.white,
        borderRadius: hp(1),
        marginTop: hp(1.30),
        borderColor: COLORS.dashboardBorder,
        borderWidth: 1,
        shadowColor: COLORS.black,
        shadowOffset: {width: 0,height: hp(0.2),},
        shadowOpacity: 0.16,
        shadowRadius: hp(1.95),
        height: hp(67.70),
    },
    pupilBoardPurple: {
        marginTop: hp(5),
        backgroundColor: COLORS.dashboardHomeWorkPurple,
    },
    pupilGridTopBg:{
        position: 'absolute',
        resizeMode: 'contain',
        width: hp(40.49),
        height:hp(10.67),
        top: hp(-9.76),
        right: hp(18.88),
    },

    date: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontBold,
        color: COLORS.darkGrayIntro,
        textAlign: 'center',
        marginBottom: hp(0.3),
    },
    today: {
        fontSize: hp(1.30),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGrayIntro,
        textAlign: 'center',
        marginBottom: hp(0.3),
    },
    datemonth: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.darkGrayIntro,
        textAlign: 'center',
    },
    moreDashboard: {
        width: 5,
        height: 28,
        resizeMode: 'contain',
        marginTop: 7,
    },
    whiteBoard: {
        width:'100%',
        backgroundColor: COLORS.white,
        borderRadius: hp(1),
        marginTop: hp(1.30),
        borderColor: COLORS.commonBorderColor,
        borderWidth: 1,
        shadowColor: COLORS.black,
        shadowOffset: {width: 0,height: hp(0.2),},
        shadowOpacity: 0.16,
        shadowRadius: hp(1.95),
        overflow: 'hidden',
    },
    timeIcon: {
        resizeMode:'contain',
        width: hp(1.76),
    },
    calIcon: {
        resizeMode:'contain',
        width: hp(1.76),
    },
    pupilBoard: {
        marginTop: hp(5),
        backgroundColor: COLORS.dashboardPupilBlue,
    },
    dashBoardBoxes: {
        flexDirection: 'row',
        marginBottom: hp(5.85),
        marginLeft: hp(-0.97),
        marginRight: hp(-0.97),
    },
    boxDash: {
        paddingLeft: hp(0.97),
        paddingRight: hp(0.97),
        width: '25%',
    },
    boxInnerMain: {
        borderRadius: hp(1.3),
        paddingLeft: hp(2),
        alignItems: 'center',
        flexDirection: 'row',
        position: 'relative',
        height: hp(12),
    },
    greenBox: {
        backgroundColor: COLORS.lightGreen,
    },
    yellowBox: {
        backgroundColor: COLORS.lightYellow,
    },
    purpleBox: {
        backgroundColor: COLORS.lightPurple,
    },
    blueBox: {
        backgroundColor: COLORS.lightBlue,
    },
    titleBox: {
        fontSize: hp(1.9),
        fontFamily: FONTS.fontSemiBold,
        position: 'relative',
        zIndex: 9,
        lineHeight: hp(2.86),
        color: COLORS.darkGrayIntro,
    },
    imageIcon: {
        position: 'absolute',
        right: 0,
        bottom: 0,
        width: hp(12.94),
        resizeMode: 'contain',
        height: hp(11.86),
    },
    leftTabbing: {
        width: '40%',
        borderRightWidth:1,
        borderColor: COLORS.commonBorderColor,
    },
    rightTabContent: {
        width: '60%',
    },
    item: {
        flexDirection: 'row',
        paddingLeft: hp(2.21),
        paddingTop: hp(2.60),
        paddingRight: hp(2.21),
        paddingBottom: hp(2.60),
        alignItems: 'center',
        justifyContent: 'space-between',
        borderColor: COLORS.commonBorderColor,
        borderBottomWidth: 1,
    },
    border: {
        height: hp(5.85),
        backgroundColor: COLORS.borderLesoon,
        padding: hp(0.39),
        borderRadius: hp(5),
        marginRight: hp(2.1),
    },
    classSubject: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    subjectName: {
        fontSize: hp(1.82),
        color: COLORS.borderLesoon,
        fontFamily: FONTS.fontSemiBold,
    },
    subject: {
        fontSize: hp(2),
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.darkGrayIntro,
    },
    subjecRow: {
        marginLeft: hp(0.8),
        flexDirection: 'row',
        alignItems: 'center',
    },
    groupName: {
        borderWidth: 1,
        borderColor: COLORS.borderGrp,
        borderRadius: 4,
        color: COLORS.grpColor,
        fontSize: hp(1.3),
        fontFamily: FONTS.fontSemiBold,
        textAlign: 'center',
        width: 52,
        height: 18,
        textAlignVertical: 'center',
    },
    timing: {
        fontSize: hp(1.82),
        color: COLORS.darkGrayIntro,
        fontFamily: FONTS.fontRegular,
    },
    tabcontent: {
        padding: hp(3.90),
        paddingBottom: hp(2.60),
        // height: hp(60),
    },
    titleTab: {
        fontSize: hp(3.125),
        fontFamily: FONTS.fontBold,
        lineHeight: hp(4.55),
        color: COLORS.darkGrayIntro,
        marginBottom: hp(1.95),
    },
    timedateGrp: {
        flexDirection: 'row',
    },
    dateWhiteBoard: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: hp(3.25),
    },
    datetimeText: {
        fontSize: hp(1.82),
        lineHeight: hp(2.60),
        marginLeft: hp(0.9),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGrayIntro,
    },
    mediaMain: {
        flexDirection: 'row',
        marginLeft: hp(-0.39),
        marginRight: hp(-0.39),
        marginBottom: hp(5),
    },
    mediabarTouch: {
        paddingLeft: hp(0.39),
        paddingRight: hp(0.39),
    },
    mediabar: {
        width: hp(4.16),
        height: hp(4.16),
        borderRadius: hp(4.16/2),
        backgroundColor: COLORS.lightGrayPupil,
    },
    moreMedia: {
        width: hp(4.16),
        height: hp(4.16),
        borderRadius: hp(200),
        backgroundColor: COLORS.white,
        borderColor: COLORS.lightGrayPupil,
        borderWidth: 1,
        justifyContent: 'center',
    },
    moreMediaText: {
        fontSize: hp(1.6),
        fontFamily: FONTS.fontRegular,
        textAlign: 'center',
    },
    lessondesciption: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontRegular,
        lineHeight: hp(2.60),
        color: COLORS.darkGrayIntro,
        marginBottom: hp(1.95),
    },
    attchmentSectionwithLink: {
        // flexDirection: 'row',
        // justifyContent: 'space-between',
        // alignItems: 'center',
    },
    downloadIcon: {
        width: hp(2.01),
        resizeMode: 'contain',
        top: hp(0.2),
        right: hp(1),
    },
    fileGrp: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: hp(1.6),
        paddingRight: hp(1.6),
        paddingTop: hp(1),
        paddingBottom: hp(1),
        borderWidth: 1,
        borderColor: COLORS.videoLinkBorder,
        borderRadius: hp(0.8),
        marginBottom: hp(1.04),
    },
    fileBoxGrpWrap: {
        // marginRight: hp(-1.5)
    },
    attachment: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    attachmentText: {
        fontSize: hp(1.82),
        lineHeight: hp(2.60),
        color: COLORS.darkGrayIntro,
        fontFamily: FONTS.fontRegular,
        marginLeft: hp(0.9),
    },
    attachmentIcon: {
        width: hp(1.5),
        resizeMode: 'contain',
    },
    linkText: {
        color: COLORS.buttonGreen,
        textTransform: 'uppercase',
        fontSize: hp(1.56),
        fontFamily: FONTS.fontBold,
    },
    // arrowSelectedTab: {
    //     width: 0,
    //     height: 0,
    //     backgroundColor: 'transparent',
    //     borderStyle: 'solid',
    //     borderTopWidth: hp(1.95),
    //     borderRightWidth: hp(1.95),
    //     borderBottomWidth: hp(1.95),
    //     borderLeftWidth: hp(1.95),
    //     position: 'absolute',
    //     right:0,
    //     // top: hp(3.90),
    //     // left: hp(-3.90),
    //     borderTopColor: 'transparent',
    //     borderRightColor: COLORS.white,
    //     borderBottomColor: 'transparent',
    //     borderLeftColor: 'transparent',
    // },
    requirementofClass: {
        marginTop: hp(4.81),
    },
    requireText: {
        fontSize: hp(2.08),
        fontFamily: FONTS.fontSemiBold,
        lineHeight: hp(2.86),
        color: COLORS.darkGrayIntro,
        marginBottom: hp(1.95),
    },
    lessonPoints: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 10,
        paddingBottom: 25,
    },
    lessonPointsBorder: {
        borderBottomColor: COLORS.borderGrp,
        borderBottomWidth: 1,
    },
    checkIcon: {
        width: hp(1.7),
        resizeMode: 'contain',
        top: hp(0.2),
    },
    lessonPointText: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGrayIntro,
        marginLeft: 10,
    },
    lessonstartButton: {
        flexDirection: 'row',
        alignSelf:'flex-end',
        marginLeft: hp(-1),
        marginRight: hp(-1),
        marginBottom: 60
    },    
    lessonstartButtonTroffy: {
        flexDirection: 'row',
        alignSelf:'center',
        marginLeft: hp(-1),
        marginRight: hp(-1),
    },    
    buttonGrp: {
        paddingLeft: 7.5,
        paddingRight: 7.5,
    },
    pupilTable: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    pupilDashboard: {
        paddingLeft: hp(3.125),
        paddingTop: hp(2.21),
        paddingRight: hp(2.21),
        paddingBottom: hp(3.51),
    },
    pupilTableHeadingMain: {
        width: hp(35.80),
    },
    tabpupil2: {
        width: hp(17.97),
    },
    tabpupil3: {
        width: hp(20.18),
        marginRight: hp(9.50),
    },
    tabpupil4: {
        width: hp(18.22),
    },
    dashboardOrangeBox:{
        backgroundColor: COLORS.orage,
        padding:hp(1),
        borderRadius: hp(1),
        position: 'relative',
        zIndex: 9,
    },
    orangeBoxTop:{
        justifyContent:'flex-end',
        zIndex: 9,
    },
    orangeBoxBottom:{
        flexDirection: 'row',
        flex: 1,
        marginTop: hp(-3),
        zIndex: 9,
    },
    pupilHeader:{
        paddingLeft: 0,
        paddingRight: 0,
        zIndex: 9,
    },
    dashboardPurpleBox:{
        backgroundColor: COLORS.dashboardHomeWorkPurple,
        padding:hp(1),
        borderRadius: hp(1),
        marginTop: hp(14.),    
    },
    purpleBoxTop:{
        justifyContent:'flex-end',
        position: 'relative',
        zIndex: 9,
    },
    myDayPurple: {
        backgroundColor: COLORS.dashboardHomeWorkPurple,
        paddingRight: hp(2.60),
        paddingLeft: hp(1.60),
        position: 'relative',
        flexDirection: 'row',
        borderRadius: hp(1),
        justifyContent: 'space-between',
        height: hp(8.5),
    },
    pupilHomeWorkGridTopBg:{
        position: 'absolute',
        resizeMode: 'contain',
        width: hp(46.87),
        height:hp(14.41),
        top: hp(-13.29),
        right: 50,
    },
    bookPositionBg: {
        position: 'absolute',
        top: hp(-8),
        right: hp(5.20),
        textAlign: 'center',
        width: hp(17.123),
        height: hp(14.84),
    },
    checkIconSquare: {
        width: 15,
        height: 15,
        resizeMode: 'contain',
        top: 3.7,
    },
    achivementWrap:{
        flexDirection: 'row',
        marginTop:hp(7.5),
        marginBottom:hp(7.5),
        width:'100%',
        alignItems: 'center',
    },
    achivementRobot:{
        width: '67%',
        shadowColor: COLORS.transparent,
        alignItems: 'center',
    },
    achivementBox:{
        borderColor: COLORS.dashboardBorder,
        borderWidth: 1,
        borderTopWidth: 0,
        width: '33%',
        alignItems:'center',
        backgroundColor:COLORS.white,
        borderRadius:6,
        // overflow:'hidden',
        paddingBottom:hp(3.8),
        shadowColor: COLORS.black,
        shadowOffset: {width: 0,height: 5,},
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 1,
        paddingLeft: hp(1.95),
        paddingRight: hp(1.95),
        paddingTop : hp(3.8)
    },
    starCovertPoints:{
        fontSize: hp(3.125),
        fontFamily: FONTS.fontBold, 
        marginBottom: hp(1.8),   
    },
    starCovert:{
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.8),
        paddingTop: hp(1.8),
    },
    rewardStar:{
        width :hp(43.48),
        height:hp(9.98),
        resizeMode: 'contain',
        marginTop: -11,
        borderTopLeftRadius: 6,
        borderTopRightRadius: 6,
    },
    rewardStarMark:{
        justifyContent: 'space-around',
        width:'100%',
        marginBottom:hp(3),
        flexDirection: 'row',
        paddingTop:hp(1.8),
        paddingBottom:hp(1.8),
        borderBottomWidth:1,
        borderBottomColor:COLORS.bottomProfileLightBorder,
        borderTopWidth:1,
        borderTopColor:COLORS.bottomProfileLightBorder,
    },
    starSelected:{
        width:hp(4.94),
        height:hp(4.68),
        resizeMode: 'contain',
        alignItems:'center',
        alignSelf: 'center',
        marginBottom: hp(1.30),
    },
    starSelectedText:{
        fontFamily: FONTS.fontBold,
        color:COLORS.white,
        fontSize: hp(1.82),
        lineHeight: hp(5.1),
    },
    centerStar:{
        borderLeftWidth:1,
        borderColor: COLORS.bottomProfileLightBorder,
        borderRightWidth:1,
        width: hp(14.32),
        alignItems: 'center',
    },
    cartoon:{
        resizeMode: 'contain',
        width:hp(57.51),
        height:hp(35.18),
    },
    starText:{
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.82),
        color: COLORS.darkGrayIntro,
    },
    centerText:{
        alignItems:'center',
    },

    // new update
    buttonView: {
        width:wp(12),
        height:Platform.OS === 'android' ? hp(5.5) : hp(5),
        backgroundColor: COLORS.dashboardGreenButton,
        color: COLORS.white,
        fontSize: hp(1.56),
        borderRadius: hp(1),
        overflow: 'hidden',
        textAlign: 'center',
        paddingLeft: hp(3.125),
        paddingRight: hp(3.125),
        paddingTop: hp(1.21),
        paddingBottom: hp(1.21),
        alignSelf: 'center',
        textTransform: 'uppercase',
        fontFamily: FONTS.fontBold,
        borderWidth: 1,
        borderColor: COLORS.dashboardGreenButton,
        marginBottom : 10
    },
    txtJointClass: {
        color: COLORS.white,
        fontSize: hp(1.56),
        overflow: 'hidden',
        textAlign: 'center',
        alignSelf: 'center',
        textTransform: 'uppercase',
        fontFamily: FONTS.fontBold,
    },
});