import { Dimensions, StyleSheet } from 'react-native'
import COLORS from '../../../utils/Colors';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import FONTS from '../../../utils/Fonts';
import { Colors } from 'react-native/Libraries/NewAppScreen';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    mainPage: {
        flexDirection: 'row',
        flex: 1,
    },
    whiteBoard: {
        backgroundColor: COLORS.white,
        borderRadius: hp(1.95),
        borderColor: COLORS.commonBorderColor,
        borderWidth: 1,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: hp(0.2), },
        shadowOpacity: 0.16,
        shadowRadius: hp(1.95),
        overflow: 'hidden',
        height: hp(65),
    },
    whiteBg: {
        backgroundColor: COLORS.white,
        paddingLeft: hp(3.5),
        paddingRight: hp(3.5),
        paddingBottom: hp(2),
        paddingTop: hp(2),
        borderBottomColor: COLORS.borderGrp,
        borderBottomWidth: 1,
    },
    lessonPlanTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    lessonPlanTab: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: hp(1.90),
    },
    tabs: {
        paddingRight: hp(3.90),
    },
    tabsText: {
        color: COLORS.menuLightFonts,
        fontFamily: FONTS.fontSemiBold,
        fontSize: hp(1.56),
        textTransform: 'uppercase',
    },
    tabsTextSelected: {
        color: COLORS.buttonGreen,
    },
    timedateGrp: {
        flexDirection: 'row',
        marginBottom: hp(4.94),
    },
    dateWhiteBoard: {
        marginRight: hp(8.7),
    },
    subjectDateTime: {
        alignItems: 'center',
        width: '100%',
    },
    datetimeText: {
        fontSize: hp(1.82),
        lineHeight: hp(2.60),
        marginLeft: hp(0.9),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
    },
    labelTextMain: {
        fontSize: hp(1.82),
        lineHeight: hp(2.60),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
    },
    calIcon: {
        resizeMode: 'contain',
        width: hp(1.76),
    },
    timeIcon: {
        resizeMode: 'contain',
        width: hp(1.76),
    },
    subjectText: {
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        color: COLORS.menuLightFonts,
        fontSize: hp(1.8),
    },
    lessonTitle: {
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        color: COLORS.menuLightFonts,
        fontSize: hp(1.8),
    },
    lessonText: {
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
        fontSize: hp(1.8),
    },
    teacherDetailLeft: {
        width: '69%',
        // borderRightWidth: 1,
        // borderColor: COLORS.borderGrp,
         paddingRight: hp(2.60),
    },
    requireText: {
        fontSize: hp(2.08),
        fontFamily: FONTS.fontSemiBold,
        lineHeight: hp(2.86),
        color: COLORS.darkGray,
        marginBottom: hp(1.95),
    },
    lessonPoints: {
        flexDirection: 'row',
        paddingBottom: hp(1.5),
        marginBottom: hp(1),
    },
    lessonPointsBorder: {
        flexDirection: 'row',
        paddingBottom: hp(1.5),
        borderBottomColor: COLORS.borderGrp,
        borderBottomWidth: 1,
        marginBottom: hp(1),
    },
    checkIcon: {
        width: hp(1.7),
        resizeMode: 'contain',
        top: hp(0.2),
    },
    lessonPointText: {
        fontSize: hp(1.85),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
        lineHeight: hp(2.60),
        marginLeft: hp(1),
    },
    requirementofClass: {
        marginTop: hp(4.81),
    },
    videoLinkBlock: {
        width: hp(36.84),
        padding: hp(1.43),
        borderWidth: 1,
        borderColor: COLORS.videoLinkBorder,
        borderRadius: hp(1.5),
        flexDirection: 'row',
    },
    videoLinkBlockSmall: {
        width: hp(24.84),
        padding: hp(1.43),
        borderWidth: 1,
        borderColor: COLORS.videoLinkBorder,
        borderRadius: hp(1.5),
        flexDirection: 'row',
    },
    videoLinkBlockSpaceTop: {
        marginTop: hp(4.81),
    },
    videoLinkBlockSpaceBottom: {
        marginBottom: hp(4.81),
    },
    videoLinkIcon: {
        width: hp(2.38),
        resizeMode: 'contain',
    },
    videoLinkText: {
        fontSize: hp(1.85),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
        lineHeight: hp(3.60),
        marginLeft: hp(1.56),
    },
    checkBoxGrp: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    checkBoxLabel: {
        flexDirection: 'row',
        width: 'auto',
        padding: hp(1.43),
        borderWidth: 1,
        borderColor: COLORS.videoLinkBorder,
        borderRadius: hp(1.5),
        marginRight: hp(1.04),
        marginBottom: hp(1.04),
        position: 'relative',
    },
    checkBoxLabelLine: {
        flexDirection: 'row',
        width: 'auto',
        paddingBottom: hp(1.30),
        marginBottom: hp(1.04),
        borderBottomWidth: 1,
        borderBottomColor: COLORS.videoLinkBorder,
    },
    checkBoxLabelText: {
        lineHeight: hp(2.82),
        fontSize: hp(1.85),
        fontFamily: FONTS.fontRegular,
        paddingLeft: hp(3.23),
    },
    checkBoxcommon: {
        position: 'absolute',
        top: hp(0.7),
    },
    toggleGrp: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomColor: COLORS.videoLinkBorder,
        borderBottomWidth: 1,
        marginBottom: hp(1.8),
        paddingBottom: hp(1.8),
    },
    toggleGrpBox: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderColor: COLORS.videoLinkBorder,
        borderWidth: 1,
        marginBottom: hp(1.8),
        padding: hp(1.1),
        borderRadius: hp(1.5),
    },
    toggleText: {
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.85),
        lineHeight: hp(3.60),
    },
    rightSideBar: {
        width: '31%',
        justifyContent: 'flex-start',
        paddingLeft: hp(2.99),
    },
    fileGrp: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingLeft: hp(1.43),
        paddingRight: hp(1.43),
        paddingTop: hp(1),
        paddingBottom: hp(0.3),
        borderWidth: 1,
        borderColor: COLORS.videoLinkBorder,
        borderRadius: hp(1.5),
        marginBottom: hp(1.04),
    },
    downloadIcon: {
        width: hp(1.95),
        resizeMode: 'contain',
    },
    fileName: {
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.85),
        lineHeight: hp(3.60),
    },
    containerWrap: {
        justifyContent: 'space-between',
        flexDirection: 'row',
    },
    grpThumbVideo: {
        width: hp(31.90),
        resizeMode: 'contain',
        alignItems: 'center',
    },
    subLineTitle: {
        marginTop: hp(-3.5),
        zIndex: 9,
    },
    closeIconSmall: {
        width: hp(2.8),
        resizeMode: 'contain',
        opacity: 0.4,
    },
    addIcon: {
        width: hp(1.56),
        resizeMode: 'contain',
    },
    addItem: {
        flexDirection: 'row',
        marginBottom: hp(2.6),
    },
    addItemText: {
        fontFamily: FONTS.fontSemiBold,
        fontSize: hp(1.56),
        color: COLORS.darkGray,
        textTransform: 'uppercase',
        paddingLeft: hp(1.3),
    },
    commonInput: {
        color: COLORS.darkGray,
        fontSize: hp('1.9%'),
        borderWidth: 1,
        borderColor: COLORS.commonBorderColor,
        overflow: 'hidden',
        borderRadius: hp('1.0%'),
        lineHeight: hp(2.3),
        height: hp('6%'),
        paddingLeft: hp('2.0%'),
        paddingRight: hp('2.0%'),
        fontFamily: FONTS.fontRegular,
    },
    recordingLinkIcon: {
        width: hp(2.34),
        resizeMode: 'contain',
    },
    recordLinkText: {
        fontSize: hp(1.85),
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.darkGray,
        lineHeight: hp(3.60),
        marginLeft: hp(1.56),
        textTransform: 'uppercase',
    },
    recordLinkBlock: {
        width: hp(23.5),
        padding: hp(1.43),
        borderWidth: 1,
        borderColor: COLORS.videoLinkBorder,
        borderRadius: hp(1.5),
        flexDirection: 'row',
    },
    recordinNormalSpaceTop: {
        marginTop: hp(1.82),
    },
    dropDownFormInput: {
        width: '50%',
    },
    duedateBox: {
        width: '47.8%',
        marginLeft: hp(1.82),
    },
    dropDown: {
        flexDirection: 'row',
        width: '95%',
        color: COLORS.darkGray,
        fontSize: hp('1.9%'),
        borderWidth: 1,
        borderColor: COLORS.commonBorderColor,
        overflow: 'hidden',
        borderRadius: hp('1.0%'),
        lineHeight: hp(2.3),
        height: hp('6%'),
        paddingLeft: hp('2.0%'),
        paddingRight: hp('2.0%'),
        paddingTop: hp('2.0%'),
        paddingBottom: hp('2.0%'),
        fontFamily: FONTS.fontRegular,
    },
    dropDownSmall: {
        flexDirection: 'row',
        width: '100%',
        color: COLORS.darkGray,
        fontSize: hp('1.9%'),
        // borderWidth: 1,
        // borderColor:COLORS.commonBorderColor,
        // overflow: 'hidden',
        // borderRadius: hp('1.0%'),
        // lineHeight:hp(2.3),
        height: hp('6%'),
        paddingLeft: hp('2.0%'),
        paddingRight: hp('2.0%'),
        paddingTop: hp('2.0%'),
        paddingBottom: hp('2.0%'),
        fontFamily: FONTS.fontRegular,
    },
    dropDownSmallWrap: {
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
        fontSize: hp('1.9%'),
        borderWidth: 1,
        borderColor: COLORS.commonBorderColor,
        overflow: 'hidden',
        borderRadius: hp('1.0%'),
        lineHeight: hp(2.3),
        height: hp('6%'),
        paddingLeft: hp('2.0%'),
        paddingRight: hp('2.0%'),
        paddingTop: hp('2.0%'),
        paddingBottom: hp('2.0%'),
    },
    textBox: {
        flexDirection: 'row',
        width: '100%',
    },
    placeholderStyle: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
    },
    rightBlockText: {
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.85),
        lineHeight: hp(2.8),
    },
    commonInputTextarea: {
        width: '100%',
        height: hp(10.67),
        borderWidth: 1,
        borderColor: COLORS.commonBorderColor,
        borderRadius: hp(1.3),
        paddingTop: hp(1.5),
        paddingBottom: hp(1.5),
        paddingRight: hp(1.5),
        paddingLeft: hp(1.5),
        marginTop: hp(1.3),
        fontSize: hp(1.82),
        color: COLORS.menuLightFonts,
        lineHeight: hp(2.60),
        fontFamily: FONTS.fontSemiBold,
    },
    commonInputTextareaNormal: {
        width: '100%',
        height: hp(10.67),
        borderWidth: 1,
        borderColor: COLORS.commonBorderColor,
        borderRadius: hp(1.3),
        paddingTop: hp(1.5),
        paddingBottom: hp(1.5),
        paddingRight: hp(1.5),
        paddingLeft: hp(1.5),
        marginTop: hp(1.3),
        fontSize: hp(1.82),
        color: COLORS.darkGray,
        lineHeight: hp(2.60),
        fontFamily: FONTS.fontRegular,
    },
    dateTime: {
        paddingTop: hp(1.5),
        paddingBottom: hp(1.5),
        paddingRight: hp(1.5),
        paddingLeft: hp(1.5),
        width: '100%',
        color: COLORS.darkGray,
        fontSize: hp('1.9%'),
        fontFamily: FONTS.fontRegular,
        lineHeight: hp(2.3),
    },
    timeField: {
        width: '31.5%',
        marginRight: hp(2.1),
    },
    blockSpaceBottom: {
        marginBottom: hp(2.6),
    },
    uploadBlock: {
        alignItems: 'center',
    },
    checkBoxGroup: {

    },
    dueDateWrap: {
        borderRightWidth: 2,
        borderRightColor: COLORS.commonBorderColor,
        marginRight: hp(1.82),
        paddingRight: hp(1.82),
    },
    dueDateText: {
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.82),
        paddingTop: hp(1.7),
        paddingBottom: hp(1.7),
    },
    dropDownSmallWrapNormal: {
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
        fontSize: hp('1.9%'),
        borderWidth: 1,
        borderColor: COLORS.commonBorderColor,
        overflow: 'hidden',
        borderRadius: hp('1.0%'),
        paddingLeft: hp('2.0%'),
        paddingRight: hp('2.0%'),
    },
    videoRecording: {
        flexDirection: 'row',
        marginTop: hp(1.6),
    },
    videoRecordSpace: {
        marginRight: hp(1.6),
    },
    // Grid Table
    pupilTable: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        height: hp(3.60),
        lineHeight: hp(3.60),
    },
    pupilDashboard: {
        paddingLeft: hp(3.125),
        paddingTop: hp(2.21),
        paddingRight: hp(2.21),
        paddingBottom: hp(3.51),
    },
    pupilTableHeadingMain: {
        width: hp(15.80),
        fontFamily: FONTS.fontRegular,
        color: COLORS.menuLightFonts,
    },
    tabpupil2: {
        width: hp(17.97),
    },
    tabpupil3: {
        width: hp(20.18),
        marginRight: hp(9.50),
    },
    tabpupil4: {
        width: hp(18.22),
    },
    pupilTableHeadingMainTitle: {
        fontSize: hp(1.5),
        lineHeight: hp(2.60),
        color: COLORS.menuLightFonts,
        fontFamily: FONTS.fontSemiBold,
        textTransform: 'uppercase',
    },
    pupilTableHeadingMainsubTitle: {
        fontSize: hp(1.56),
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.menuLightFonts,
        textTransform: 'uppercase',
        lineHeight: hp(2.08),
        marginRight: hp(2.60),
    },
    pupilTableHeadingMainsubTitlestar: {
        fontSize: hp(1.56),
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.menuLightFonts,
        textTransform: 'uppercase',
        lineHeight: hp(2.08),
        marginRight: hp(0.91),
    },
    pupilTableHeadingsubMain: {
        flexDirection: 'row',
    },
    pupilhrCustomMargin: {
        marginTop: hp(1.95),
        marginBottom: hp(1.30),
    },
    pupilData: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1, },
        elevation: 3,
        borderRadius: hp(1.95),
        height: hp(8.85),
        borderRadius: hp(2.0),
    },
    pupilProfile: {
        width: hp(15.80),
        flexDirection: 'row',
        alignItems: 'center',
    },
    groupColumnmain: {
        width: hp(17.97),
    },
    groupColumn: {
        width: hp(5.59),
        alignItems: 'center',
    },
    pupilgroupName: {
        textAlign: 'center',
    },
    perfomanceColumn: {
        flexDirection: 'row',
        width: hp(20.18),
        marginRight: hp(9.50),
    },
    perfomanceDotmain: {
        width: hp(10.80),
        alignItems: 'center',
        marginRight: hp(2.60),
    },
    perfomanceDotmainTwo: {
        width: hp(7),
        alignItems: 'center',
    },
    perfomanceDots: {
        width: hp(1.1),
        height: hp(1.1),
        borderRadius: hp(100),
    },
    purpleDot: {
        backgroundColor: COLORS.purpleDark,
    },
    yellowDot: {
        backgroundColor: COLORS.yellowDark,
    },
    rewardColumn: {
        flexDirection: 'row',
    },
    rewardStar: {
        width: hp(5.5),
        marginRight: hp(0.91),
    },
    rewardStartIcon: {
        width: hp(2.15),
        resizeMode: 'contain',
        alignSelf: 'center',
    },
    pupilDetailLink: {
        width: hp(10),
        alignItems: 'flex-end',
    },
    pupilDetaillinkIcon: {
        width: hp(1),
        resizeMode: 'contain',
    },
    pupilImage: {
        width: hp(3.7),
        height: hp(3.7),
        borderRadius: hp(100),
        backgroundColor: COLORS.lightGrayPupil,
        marginRight: hp(1.69),
    },
    pupilName: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
    },
    pupilgroupName: {
        fontSize: hp(1.82),
        fontFamily: FONTS.fontRegular,
        color: COLORS.darkGray,
    },
    border: {
        height: hp(5.85),
        backgroundColor: '#71C4E4',
        padding: 3,
        borderRadius: hp(5),
        marginRight: hp(2.1),
        marginLeft: hp(1.8),
        width: hp(0.5),
        position: 'absolute',
        top: hp(-1.5),
    },
    firstColumn: {
        paddingLeft: hp(4.5),
        width: hp(34.55),
    },
    secoundColumn: {
        width: hp(22.55),
    },
    lastColumn: {
        width: hp(20.55),
        justifyContent: 'space-between',
    },
    yesText: {
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.dashboardPupilBlue,
        fontSize: hp(1.82),
    },
    noText: {
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.yellowDark,
        fontSize: hp(1.82),
    },
    markText: {
        fontFamily: FONTS.fontSemiBold,
        color: COLORS.purpleDark,
        fontSize: hp(1.82),
    },
    userStamp: {
        height: hp(3.64),
        width: hp(3.64),
        backgroundColor: COLORS.lightGrayPupil,
        borderRadius: hp(5),
        marginRight: hp(2.1),
        position: 'absolute',
        top: hp(-0.5),
        left: hp(3.5),
    },
    userStampName: {
        paddingLeft:hp(4.0),
    },
    uploadBoard:{
        width:hp(33.07),
        height:hp(45.05),
        resizeMode:'contain',
    },
    containerWrapTop: {
        justifyContent: 'space-between',
        flexDirection: 'row',
        borderWidth:1,
        borderColor:COLORS.lightGrayPupil,
        borderRadius:hp(1.5),
        marginBottom:hp(2),
        padding:hp(1),
    },
    userThumb:{
        width:hp(6.25), 
        height:hp(6.25), 
        backgroundColor: COLORS.lightGrayPupil,  
        borderRadius: hp(5), 
        marginRight:hp(1.30),
    },
    userLeft:{
       width:'55%',
       flexDirection: 'row',
    },
    userRight:{
        width:'45%',
        flexDirection: 'row',
    },
    userTopName:{
        flexDirection: 'row',
        fontFamily: FONTS.fontSemiBold,
        fontSize:hp(2.08),
        color:COLORS.darkGray,
    },
    userTopGroup:{
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        fontSize:hp(1.82),
        color:COLORS.menuLightFonts,
    },
    dateTitle:{
        flexDirection: 'row',
        fontFamily: FONTS.fontSemiBold,
        fontSize:hp(1.56),
        color:COLORS.menuLightFonts,
        textTransform:'uppercase',
    },
    dateText:{
        flexDirection: 'row',
        fontFamily: FONTS.fontRegular,
        fontSize:hp(1.82),
        color:COLORS.darkGray,
    },
    markedIcon:{
        width:hp(2.13),
        resizeMode:'contain',
        marginRight:hp(1),
    },
    markedLabel:{
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginRight:hp(9.63),
        marginTop:hp(1.5),
    },
    markedText:{
        fontFamily: FONTS.fontRegular,
        fontSize:hp(1.82),
        color:COLORS.darkGray,
        lineHeight:hp(3.2),
    },
    dateNameBlock:{
        marginRight:hp(2.21),
        marginTop:hp(1),
    },
    feedbackBlock:{
        width:'60%',
    },
    ratingBlock:{
        width:'40%',
        marginLeft:hp(1.95),
    },
    lessonTitleBold:{
        fontFamily: FONTS.fontSemiBold,
        fontSize:hp(2.08),
        color:COLORS.darkGray,
    },
    achivementBox:{
        borderColor: COLORS.dashboardBorder,
        borderWidth: 1,
        width :hp(43.48),
        alignItems:'center',
        backgroundColor:COLORS.white,
        borderRadius:hp(1.8),
        overflow:'hidden',
        shadowColor: "#000",
        shadowOffset: {width: 0,height: 5,},
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 1,
        paddingLeft: hp(1.95),
        paddingRight: hp(1.95),
    },
    starSelectedText:{
        fontFamily: FONTS.fontBold,
        color:COLORS.white,
        fontSize: hp(1.82),
        lineHeight: hp(5.1),
    },
    starSelected:{
        width:hp(4.94),
        height:hp(4.68),
        resizeMode: 'contain',
        alignItems:'center',
        alignSelf: 'center',
    },
    rewardStarMark:{
        justifyContent: 'space-around',
        width:'100%',
        flexDirection: 'row',
        paddingTop:hp(1.8),
        paddingBottom:hp(1.8),
    },
    centerText:{
        alignItems:'center',
    },
    starText:{
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.82),
        color: COLORS.darkGray,
    },
    ratingTitle:{
        fontFamily: FONTS.fontRegular,
        fontSize: hp(1.82),
        color:COLORS.menuLightFonts,
        paddingBottom:hp(1.5),
    },
    separater:{
        borderLeftWidth:1,
        borderLeftColor:COLORS.dashboardBorder,
        borderRightWidth:1,
        borderRightColor:COLORS.dashboardBorder,
        width:hp(14.32),
    },
    centerStar:{
        alignItems:'center',
    },
    videoTitle:{
        fontFamily:FONTS.fontSemiBold,
        fontSize:hp(2.08),
        color: COLORS.darkGray,
    },
    videoWrap:{
        flexDirection:'row',
        justifyContent:'flex-start',
        flexWrap:'wrap',
    },  
    videoThumb:{
        position:'relative',
        flexDirection:'row',
        marginRight:hp(4.10),
    },
    videoThumbnail:{        
        width:hp(26.17),
        height:hp(17.83),
        resizeMode:'contain',
    },
    videoPlay:{
        width:hp(5.20),
        resizeMode:'contain',
        position:'absolute',
        top:hp(5.5),
        left:hp(11.32),
    },
    videoSelected:{
        width:hp(2.17),
        resizeMode:'contain',
        position:'absolute',
        bottom:hp(1),
        right:hp(1.24),
    },
    videoSubTitle:{
        fontFamily:FONTS.fontRegular,
        fontSize:hp(1.82),
        color: COLORS.darkGray,
        flexDirection:'row',
        lineHeight:hp(1.82),
        paddingTop:hp(1.5),
        paddingBottom:hp(1.5),
        width:hp(26.17),
        flexWrap:'wrap',
        marginBottom:hp(1.20),
    },
    spaceTop:{
        marginTop:hp(3.5),
    },
    rightSpaceNone:{
        marginRight:hp(0),
    },
});